# Generated by Django 3.0.5 on 2020-11-30 23:47

import course.models
from django.db import migrations, models
import django.db.models.deletion
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('subject_number', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=64)),
                ('subject', models.CharField(max_length=64)),
                ('number', models.CharField(max_length=64)),
                ('prerequsite', models.CharField(max_length=512)),
                ('introduction', models.CharField(max_length=512)),
                ('average_workload', models.IntegerField()),
                ('average_rating', models.IntegerField()),
            ],
            options={
                'db_table': 'Course',
            },
        ),
        migrations.CreateModel(
            name='GeneralEducation',
            fields=[
                ('type', models.CharField(max_length=64, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'GeneralEducation',
            },
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('year_term', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('year', models.CharField(max_length=64)),
                ('term', models.CharField(max_length=64)),
            ],
            options={
                'db_table': 'Semester',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('subject_number', models.CharField(max_length=64)),
                ('subject', models.CharField(max_length=64)),
                ('number', models.CharField(max_length=64)),
                ('content', models.CharField(max_length=512)),
                ('user', djongo.models.fields.ArrayField(model_container=course.models.User, model_form_class=course.models.UserForm)),
            ],
            options={
                'db_table': 'Tag',
            },
        ),
        migrations.CreateModel(
            name='UserInput',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=512)),
                ('workload', models.IntegerField(default=-1)),
                ('rating', models.IntegerField(default=-1)),
                ('subject_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.Course')),
            ],
            options={
                'db_table': 'UserInput',
            },
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=64)),
                ('middle_name', models.CharField(max_length=64)),
                ('last_name', models.CharField(max_length=64)),
                ('a_plus', models.IntegerField()),
                ('a', models.IntegerField()),
                ('a_minus', models.IntegerField()),
                ('b_plus', models.IntegerField()),
                ('b', models.IntegerField()),
                ('b_minus', models.IntegerField()),
                ('c_plus', models.IntegerField()),
                ('c', models.IntegerField()),
                ('c_minus', models.IntegerField()),
                ('d_plus', models.IntegerField()),
                ('d', models.IntegerField()),
                ('d_minus', models.IntegerField()),
                ('w', models.IntegerField()),
                ('f', models.IntegerField()),
                ('subject_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.Course')),
                ('year_term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.Semester')),
            ],
            options={
                'db_table': 'Grade',
            },
        ),
        migrations.CreateModel(
            name='GenedSatisfaction',
            fields=[
                ('subject_number_type', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('subject_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.Course')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.GeneralEducation')),
            ],
            options={
                'db_table': 'GenedSatisfaction',
            },
        ),
    ]
